{"uuid": "a235c3b5-16da-467f-aeb3-2925b63e18c7", "children": ["6f0e5162-a0fa-4e72-9ce3-e8c4c7566273"], "befores": [{"name": "browsers", "status": "passed", "start": 1753252681466, "stop": 1753252689137}], "afters": [{"name": "browsers::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: chrome=138.0.7204.158)\nStacktrace:\n\tGetHandleVerifier [0x0x331af3+62339]\n\tGetHandleVerifier [0x0x331b34+62404]\n\t(No symbol) [0x0x172123]\n\t(No symbol) [0x0x160698]\n\t(No symbol) [0x0x16161d]\n\t(No symbol) [0x0x172b33]\n\t(No symbol) [0x0x150b45]\n\t(No symbol) [0x0x1ed8ae]\n\t(No symbol) [0x0x1df383]\n\t(No symbol) [0x0x1ae7a2]\n\t(No symbol) [0x0x1af644]\n\tGetHandleVerifier [0x0x5a6683+2637587]\n\tGetHandleVerifier [0x0x5a1a8a+2618138]\n\tGetHandleVerifier [0x0x35856a+220666]\n\tGetHandleVerifier [0x0x348998+156200]\n\tGetHandleVerifier [0x0x34f12d+182717]\n\tGetHandleVerifier [0x0x339a38+94920]\n\tGetHandleVerifier [0x0x339bc2+95314]\n\tGetHandleVerifier [0x0x324d0a+9626]\n\tBaseThreadInitThunk [0x0x75acfcc9+25]\n\tRtlGetAppContainerNamedObjectPath [0x0x772182ae+286]\n\tRtlGetAppContainerNamedObjectPath [0x0x7721827e+238]\n\t(No symbol) [0x0]\n\n", "trace": "  File \"C:\\Users\\Devils Den\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Devils Den\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Devils Den\\Python_Practice_1\\Green_Kart\\conftest.py\", line 29, in browsers\n    driver.close()\n  File \"C:\\Users\\Devils Den\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 598, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\Devils Den\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 448, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Devils Den\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1753252693771, "stop": 1753252693823}], "start": 1753252681466, "stop": 1753252693823}